In [ ]:
w1, w2, b = 0.5, 0.5, -1

def activate(x):
    return 1 if x >= 0 else 0

def train_perceptron(inputs, desired_outputs, learning_rate, epochs):
    global w1, w2, b
    for epoch in range(epochs):
        total_error = 0
        for i in range(len(inputs)):
            A, B = inputs[i]
            target_output = desired_outputs[i]
            output = activate(w1 * A + w2 * B + b)
            error = target_output - output
            w1 += learning_rate * error * A
            w2 += learning_rate * error * B
            b += learning_rate * error
            total_error += abs(error)
            print(A);
            print(B);
        if total_error == 0:
            break


inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
desired_outputs = [0, 0, 0, 1]
learning_rate = 0.1
epochs = 100

train_perceptron(inputs, desired_outputs, learning_rate, epochs)

for i in range(len(inputs)):
    A, B = inputs[i]
    output = activate(w1 * A + w2 * B + b)
    print(f"Input: ({A}, {B})  Output: {output}")

0
0
0
1
1
0
1
1
Input: (0, 0)  Output: 0
Input: (0, 1)  Output: 0
Input: (1, 0)  Output: 0
Input: (1, 1)  Output: 1


In [ ]:
import numpy as np

# Define the step function
def step_function(x):
    return 1 if x > 0 else 0

# Define the training data
X = np.array([
    [1, 0, 0, 1],
    [1, 0, 0, 0],
    [0, 0, 1, 1],
    [0, 1, 0, 0],
    [1, 1, 0, 1],
    [0, 0, 1, 1],
    [0, 0, 0, 1],
    [0, 0, 1, 0]
])

Y = np.array([1, 1, 0, 0, 1, 1, 0, 0])

# Initialize weights and bias
weights = np.array([0.1, 0.2, 0.3, 0.4])
bias = 0.5
learning_rate = 0.1

# Training loop
for iteration in range(5000):
    for i in range(len(X)):
        input_data = X[i]
        target = Y[i]

        # Calculate the predicted output
        predicted_output = step_function(np.dot(input_data, weights) + bias)

        # Calculate the error
        error = target - predicted_output

        # Update the weights and bias using the Delta Learning Rule
        weights += learning_rate * error * input_data
        bias += learning_rate * error

        # Print the weights on each iteration
        if iteration % 100 == 0:  # Print every 100 iterations
            print(f"Iteration {iteration}: Weights = {weights}, Bias = {bias}")

# Final weights after training
print("\nFinal weights after 5000 iterations:")
print(weights)
print("Final bias:")
print(bias)

# Test with new data
test_data = np.array([
    [1, 0, 0, 1],
    [0, 0, 1, 0],
    [1, 0, 1, 0]
])

print("\nTesting the perceptron:")
for data in test_data:
    predicted_output = step_function(np.dot(data, weights) + bias)
    print("Input:", data, "Predicted Output:", predicted_output)


Iteration 0: Weights = [0.1 0.2 0.3 0.4], Bias = 0.5
Iteration 0: Weights = [0.1 0.2 0.3 0.4], Bias = 0.5
Iteration 0: Weights = [0.1 0.2 0.2 0.3], Bias = 0.4
Iteration 0: Weights = [0.1 0.1 0.2 0.3], Bias = 0.30000000000000004
Iteration 0: Weights = [0.1 0.1 0.2 0.3], Bias = 0.30000000000000004
Iteration 0: Weights = [0.1 0.1 0.2 0.3], Bias = 0.30000000000000004
Iteration 0: Weights = [0.1 0.1 0.2 0.2], Bias = 0.20000000000000004
Iteration 0: Weights = [0.1 0.1 0.1 0.2], Bias = 0.10000000000000003
Iteration 100: Weights = [3.00000000e-01 1.00000000e-01 2.00000000e-01 2.77555756e-17], Bias = -0.19999999999999998
Iteration 100: Weights = [3.00000000e-01 1.00000000e-01 2.00000000e-01 2.77555756e-17], Bias = -0.19999999999999998
Iteration 100: Weights = [ 0.3  0.1  0.1 -0.1], Bias = -0.3
Iteration 100: Weights = [ 0.3  0.1  0.1 -0.1], Bias = -0.3
Iteration 100: Weights = [ 0.3  0.1  0.1 -0.1], Bias = -0.3
Iteration 100: Weights = [3.00000000e-01 1.00000000e-01 2.00000000e-01 2.77555756e-1

In [3]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def dsigmoid(x):
    return x * (1 - x)

def forward_pass(x, w1, w2, w3, b1, b2, b3):
    z1 = np.dot(x, w1) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(a1, w2) + b2
    a2 = sigmoid(z2)

    z3 = np.dot(a2, w3) + b3
    a3 = sigmoid(z3)

    return a1, a2, a3

def backward_pass(x, y, a1, a2, a3, w1, w2, w3, b1, b2, b3, η):
    delta3 = y - a3
    d3 = dsigmoid(a3) * delta3

    delta2 = np.dot(d3, w3.T)
    d2 = dsigmoid(a2) * delta2

    delta1 = np.dot(d2, w2.T)
    d1 = dsigmoid(a1) * delta1

    dw1 = η * np.dot(x.T, d1)
    db1 = η * np.sum(d1)

    dw2 = η * np.dot(a1.T, d2)
    db2 = η * np.sum(d2)

    dw3 = η * np.dot(a2.T, d3)
    db3 = η * np.sum(d3)

    return dw1, db1, dw2, db2, dw3, db3

def update_weights(w1, w2, w3, b1, b2, b3, dw1, db1, dw2, db2, dw3, db3):
    w1 += dw1
    b1 += db1
    w2 += dw2
    b2 += db2
    w3 += dw3
    b3 += db3

    return w1, w2, w3, b1, b2, b3

def train(x, y, w1, w2, w3, η, num_iterations, print_iterations):
    b1 = np.zeros((1, w1.shape[1]))  # Initialize bias for the first layer
    b2 = np.zeros((1, w2.shape[1]))  # Initialize bias for the second layer
    b3 = np.zeros((1, w3.shape[1]))  # Initialize bias for the output layer

    for iteration in range(num_iterations+1):
        a1, a2, a3 = forward_pass(x, w1, w2, w3, b1, b2, b3)

        dw1, db1, dw2, db2, dw3, db3 = backward_pass(x, y, a1, a2, a3, w1, w2, w3, b1, b2, b3, η)

        w1, w2, w3, b1, b2, b3 = update_weights(w1, w2, w3, b1, b2, b3, dw1, db1, dw2, db2, dw3, db3)

        if np.isin(iteration, print_iterations):
            print(f"Iteration {iteration}:")
            print("w1:")
            print(w1)
            print("w2:")
            print(w2)
            print("w3:")
            print(w3)
            print("b1:", b1)
            print("b2:", b2)
            print("b3:", b3)
            print("")

    return w1, w2, w3, b1, b2, b3

# Define the training data and target labels
x = np.array([
    [0.6, 0.1],
    [0.2, 0.3]
])

y = np.array([
    [1, 0],
    [0, 1]
])

# Define the initial weights and learning rate
w1 = np.random.rand(x.shape[1], 2)
w2 = np.random.rand(2, 2)
w3 = np.random.rand(2, y.shape[1])
η = 0.1
num_iterations = 50
print_iterations = [1, 2, 50]

# Train the neural network
w1, w2, w3, b1, b2, b3 = train(x, y, w1, w2, w3, η, num_iterations, print_iterations)


Iteration 1:
w1:
[[0.60726314 0.16615299]
 [0.50186968 0.60773882]]
w2:
[[0.02225686 0.89909331]
 [0.40203033 0.68607841]]
w3:
[[0.12035534 0.2439982 ]
 [0.62033259 0.14461884]]
b1: [[-0.00074928 -0.00074928]]
b2: [[-0.00242649 -0.00242649]]
b3: [[-0.01757684 -0.01757684]]

Iteration 2:
w1:
[[0.60728769 0.16614616]
 [0.50178327 0.60767393]]
w2:
[[0.02204895 0.89865639]
 [0.40185406 0.68561765]]
w3:
[[0.11718193 0.24249683]
 [0.61635661 0.14263106]]
b1: [[-0.00110537 -0.00110537]]
b2: [[-0.00357323 -0.00357323]]
b3: [[-0.02596574 -0.02596574]]

Iteration 50:
w1:
[[0.60991832 0.16715882]
 [0.49860005 0.60561954]]
w2:
[[0.01826215 0.88870186]
 [0.39942848 0.67390065]]
w3:
[[0.02774748 0.22276692]
 [0.50576532 0.11383679]]
b1: [[-0.00964528 -0.00964528]]
b2: [[-0.02879557 -0.02879557]]
b3: [[-0.22329024 -0.22329024]]



In [ ]:
import numpy as np

# Define the dataset and class labels
data = np.array([
    ['sunny', 'hot', 'high', 'weak', 'Not Play'],
    ['sunny', 'hot', 'high', 'strong', 'Not Play'],
    ['overcast', 'hot', 'high', 'weak', 'Play'],
    ['rain', 'mild', 'high', 'weak', 'Play'],
    ['rain', 'cool', 'normal', 'weak', 'Play'],
    ['rain', 'cool', 'normal', 'strong', 'Not Play'],
    ['overcast', 'cool', 'normal', 'strong', 'Play'],
    ['sunny', 'mild', 'high', 'weak', 'Not Play'],
    ['sunny', 'cool', 'normal', 'weak', 'Play'],
    ['rain', 'mild', 'normal', 'weak', 'Play'],
    ['sunny', 'mild', 'normal', 'strong', 'Play'],
    ['overcast', 'mild', 'high', 'strong', 'Play'],
    ['overcast', 'hot', 'normal', 'weak', 'Play'],
    ['rain', 'mild', 'high', 'strong', 'Not Play']
])

# Define the new sample
new_sample = ['sunny', 'cool', 'high', 'weak']

# Calculate the total number of instances and class probabilities
total_instances = len(data)
play_probability = np.count_nonzero(data[:, 4] == 'Play') / total_instances
not_play_probability = np.count_nonzero(data[:, 4] == 'Not Play') / total_instances

# Initialize dictionaries to store conditional probabilities for each class
play_conditional_probabilities = {}
not_play_conditional_probabilities = {}

# Calculate conditional probabilities for the 'Play' class
for i in range(4):
    feature_values = data[data[:, 4] == 'Play', i]
    unique_feature_values = np.unique(data[:, i])
    for value in unique_feature_values:
        count = np.count_nonzero(feature_values == value)
        play_conditional_probabilities[(i, value)] = count / len(feature_values)

# Calculate conditional probabilities for the 'Not Play' class
for i in range(4):
    feature_values = data[data[:, 4] == 'Not Play', i]
    unique_feature_values = np.unique(data[:, i])
    for value in unique_feature_values:
        count = np.count_nonzero(feature_values == value)
        not_play_conditional_probabilities[(i, value)] = count / len(feature_values)

# Calculate the probability of the new sample for both classes
play_probability_new_sample = play_probability
not_play_probability_new_sample = not_play_probability

for i in range(4):
    feature_value = new_sample[i]
    play_probability_new_sample *= play_conditional_probabilities[(i, feature_value)]
    not_play_probability_new_sample *= not_play_conditional_probabilities[(i, feature_value)]

# Compare the probabilities to determine the most likely class
if play_probability_new_sample > not_play_probability_new_sample:
    print("The new sample is classified as 'Play' using the Bayesian classifier.")
else:
    print("The new sample is classified as 'Not Play' using the Bayesian classifier.")


The new sample is classified as 'Not Play' using the Bayesian classifier.
